### ISSUE TITLE
need to upgrade to a newwer GNOME runtime

### ISSUE THREAD

**Issue by mMerlin** [flathub/com.github.labyrinth_team.labyrinth#2]
```sh
% flatpak update
Looking for updates…
Info: org.gnome.Platform is end-of-life, with reason: The GNOME 3.34 runtime is no longer supported as of 14th August 2020. Please ask your application developer to migrate to a supported platform.
Info: org.gnome.Platform.Locale is end-of-life, with reason: The GNOME 3.34 runtime is no longer supported as of 14th August 2020. Please ask your application developer to migrate to a supported platform.

%flatpak list --app --columns=name,runtime | grep "3\.34"   
Labyrinth	org.gnome.Platform/x86_64/3.34

% flatpak info com.github.labyrinth_team.labyrinth

Labyrinth - A light weight mind mapping tool

          ID: com.github.labyrinth_team.labyrinth
         Ref: app/com.github.labyrinth_team.labyrinth/x86_64/stable
        Arch: x86_64
      Branch: stable
     Version: 0.6
     License: GPL-2.0
      Origin: flathub
  Collection: org.flathub.Stable
Installation: user
   Installed: 91.3 MB
     Runtime: org.gnome.Platform/x86_64/3.34
         Sdk: org.gnome.Sdk/x86_64/3.34

      Commit: 1b1ff107a6ef87cbf3c6670162e1c75146a0308bc501c46267a9cb4b6141253a
      Parent: 09611ff95e2444e5a7e6219a633f1134becab0c6b8ea3b08415dfd98e21f474b
     Subject: Rename & install the metainfo (1873027c)
        Date: 2020-01-26 19:04:51 +0000
```

**Comment by takluyver** [comment]
Do you want to make a PR to upgrade it? It's controlled by this file: https://github.com/flathub/com.github.labyrinth_team.labyrinth/blob/master/com.github.labyrinth_team.labyrinth.json

**Comment by mMerlin** [comment]
I could create a PR for that easy enough, but am not really setup to build and test the result. I do not know enough about what to look for either. I use flatpak apps, but have never created or built one.

**Comment by takluyver** [comment]
Flathub's really nice on that point - when you open a PR, it will build the changes and give you a command to install the result so you can test it. :-)

**Comment by mMerlin** [comment]
Nice. I'll see about giving that a try tomorrow. After 02:00 AM here, so not a good idea to start something new just now.

**Comment by takluyver** [comment]
Definitely sensible, get some sleep! :sleeping:

**Comment by mMerlin** [comment]
Well, that is not working so well. Smoke test works, but fails on export. Not "FAILS", but the exported file is apparently hiding someplace in the flatpak. I can't find where it went.

**Comment by takluyver** [comment]
I think that's actually the same in the version already on Flathub. The proper fix is to migrate to GTK 3, which can use 'Portals' to save & load files from outside the sandbox. That has been [stuck for years](https://github.com/labyrinth-team/labyrinth/issues/1) because the Pango library can't be fully used from Python with the new GObject introspection system. Although it's hardly 'new' any more, Pango still doesn't fully work with it.

Until then, it could be worked around by exposing the home directory to Labyrinth - effectively disabling the sandbox. It would be a bit of a shame, because apart from that Labyrinth plays nicely with the sandbox. *Shrug*

**Comment by mMerlin** [comment]
Then it is ready to go.

I had it around to compare with other mind map tools. Was not *seriously* using it, so had not explored that part.
