### ISSUE TITLE
Include pygtk shared-module

### ISSUE THREAD

**Issue by Eonfge** [flathub/com.github.labyrinth_team.labyrinth#4]
Hey, 

I copy-pasted your python 2 - gtk 2 modules and it's now available as a shared module:
https://github.com/flathub/shared-modules/pull/138

You're project would be an ideal candidate to use pygtk from the /shared-modules/ since it saves us all from double maintenance:
https://github.com/flathub/shared-modules/tree/master/pygtk

**Comment by takluyver** [comment]
Thanks! If and when I get back to labyrinth, though, it would likely be to finally finish adapting it to GTK 3 and the new gobject introspection system.
